### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-sonoff

### ISSUE THREAD

**Issue by CiTroNaK** [AlexanderBabel/homebridge-sonoff#2]
Hi,
thank you for your work. I've encountered a problem while trying to use it. Could you please be so kind and help me?

node: v6.14.4
homebridge: 0.4.45

```
[10. 1. 2019 9:55:09] ERROR LOADING PLUGIN homebridge-sonoff:
[10. 1. 2019 9:55:09] /usr/local/lib/node_modules/homebridge-sonoff/index.js:100
    .on('get', async (callback) => {
                    ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
[10. 1. 2019 9:55:09] ====================
```

Thank you very much.

Best regards,
Petr

**Comment by AlexanderBabel** [comment]
Hey Petr,

please use a newer node version. I recommend version 8 or above.

Version 6 is a outdated version of node which don’t receive any security updates from NodeJS.

Greetings
Alex

**Comment by CiTroNaK** [comment]
Helped. Thank you.
