### ISSUE TITLE
Switch state

### ISSUE THREAD

**Issue by tamasharasztosi** [AlexanderBabel/homebridge-sonoff#5]
Hi! First of all great work, thank you!
I found out that state not working right now.
With "http://sonoff/?m=1" http command the response is "{t}{t}OFF" or "{t}{t}ON" depending on the current state. It does not require authentication.
Could we refresh this code to make it work?

**Comment by AlexanderBabel** [comment]
Hey there,

sorry for my very late answer. I updated the plugin to work with the newest version of the Tasmota firmware.

Hope everything will work as expected. If not feel free to reopen this issue!

Have a nice day!

**Comment by tamasharasztosi** [comment]
Okay I updated and got this error message when starting homebridge:

TypeError: Cannot read property 'devices' of null
    at new Sonoff (/usr/local/lib/node_modules/homebridge-sonoff/index.js:16:45)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by AlexanderBabel** [comment]
It looks like you do not have a platform config defined.

**Comment by tamasharasztosi** [comment]
Thank you!:)
